package com.fintech.orchestration.domain;

public enum SagaState {
    CUSTOMER_CREATED,
    ACCOUNT_CREATION,
    ACCOUNT_CREATED,
    WALLET_CREATION,
    WALLET_CREATED,
    LEDGER_ACCOUNT_CREATION,
    LEDGER_ACCOUNT_CREATED,
    LEDGER_ENTRIES_CREATION,
    LEDGER_ENTRIES_CREATED,
    ACCOUNT_ACTIVATION,
    ACCOUNT_ACTIVATED,
    TRANSACTION_INITIATED,
    TRANSACTION_HANDLE,
    WALLET_UPDATE,
    WALLET_CREDITED,
    FUND_RESERVATION,
    FUND_RESERVED,
    WALLET_DEBITED,
    WALLET_TRANSFERRED
}
