server:
  port: 8082

spring:
  application:
    name: orchestration-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orchestration_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        #type:
         # json_format_mapper: com.fintech.common.mapper.Jackson3FormatMapper

  kafka:
    bootstrap-servers: 172.22.92.202:9092
    producer:
      # Defining this prefix auto-enables Spring Boot 4 Kafka transaction managers
      #transaction-id-prefix: tx-orchestration-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true
    consumer:
      group-id: orchestration-services
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fintech-realm

  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env

outbox:
  poller:
    fixed-delay-ms: 5000
    batch-size: 50
    retry-limit: 5

saga:
  timeout:
    fixed-delay-ms: 60000
    batch-size: 50
  retry:
    fixed-delay-ms: 60000
    batch-size: 50
    limit: 3

feign:
  client:
    config:
      transaction-service:
        connectTimeout: ${TRANSACTION_CONNECT_TIMEOUT:1500}
        readTimeout: ${TRANSACTION_READ_TIMEOUT:2500}

resilience4j:
  circuitbreaker:
    metrics:
      enabled: false
    instances:
      transactionServiceCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      transactionServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
  timelimiter:
    instances:
      transactionServiceTL:
        timeout-duration: 3s

clients:
  transaction-service:
    url: http://localhost:8085

keycloak:
  token-url: http://localhost:9090/realms/fintech-realm/protocol/openid-connect/token
  client-id: fintech-client
  client-secret: tBCgqZX6GM0Irm9q0VCWHhFhFBpqAuOR

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.tool.hbm2ddl: WARN
    org.springframework.kafka: INFO
    org.springframework.web: INFO


