server:
  port: 8086

spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: 172.22.92.202:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true
    consumer:
      group-id: fraud-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

outbox:
  poller:
    fixed-delay-ms: 5000
    batch-size: 50
    retry-limit: 5

logging:
  level:
    root: INFO
