server:
  port: 8087

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: 172.22.92.202:9092
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        enable.idempotence: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/fintech-realm

  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.kafka: INFO
    org.springframework.web: DEBUG

keycloak:
  token-url: http://localhost:9090/realms/fintech-realm/protocol/openid-connect/token
  client-id: fintech-client
  client-secret: tBCgqZX6GM0Irm9q0VCWHhFhFBpqAuOR
